name: 'PR name check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@v1
        with:
          # Match pull request titles in the form of:
          # Release/s123 
          # dev => canary
          # canary => dev
          # canary => master
          # master => dev
          # MOBILE-123123 - fix bug
          # MOBILE-123123 MOBILE-34534 - fix bug
          # hotfix/MOBILE-123123 - fix sueprbug
          # Revert MOBILE-123123 - revert because Lu didn't like it
          pattern: '^((((hotfix\/|Revert\s|)(MOBILE|IL|NYC|CLINICAL|CUSTOMER|CORE|DS)-\d*\s)+-\s.+)|Release\/s\d+|canary => dev|canary => master|master => dev|dev => canary)'
